;TYPE=PLATED
;Layer: NPTH_Through
;EasyEDA Pro Client v2.2.27.1, 2024-09-15 10:59:51
;Gerber Generator version 0.3
M48
; DRILL file {KiCad 9.0.0} date 2025-03-31T22:32:46+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-31T22:32:46+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
%
G90
G05
M30
