;TYPE=PLATED
;Layer: NPTH_Through
;EasyEDA Pro Client v2.1.63.af010a1c.225d47, 2024-08-20 20:16:00
;Gerber Generator version 0.3
M48
; DRILL file {KiCad 8.0.4} date 2024-08-27T14:50:52+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-27T14:50:52+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
%
G90
G05
M30
